import React, { useEffect } from 'react'

export const Home = () => {
  return (
    <div>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
      <p>home</p>
    </div>
  )
}
